# Generated by Django 4.1.7 on 2023-03-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="This field is private",
                        max_length=254,
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, help_text="handle without @", max_length=255
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True, help_text="handle only", max_length=255
                    ),
                ),
                ("photo", models.ImageField(upload_to="team/")),
                ("published", models.BooleanField(default=False)),
            ],
        )
    ]
