# Generated by Django 4.1.7 on 2023-04-01 12:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("content", wagtail.fields.RichTextField(blank=True)),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="email",
            field=models.EmailField(
                blank=True, default="", help_text="private field", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="photo",
            field=models.ImageField(upload_to="photos/team"),
        ),
    ]
