# Generated by Django 4.1.7 on 2023-04-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_teampage_alter_organizer_email_alter_organizer_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizer",
            name="photo",
            field=models.ImageField(upload_to="team/images/"),
        ),
    ]
