# Generated by Django 4.2.1 on 2023-08-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_teampage_alter_organizer_email_alter_organizer_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="linkedin",
            field=models.URLField(blank=True, help_text="full URL", null=True),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="github",
            field=models.URLField(blank=True, help_text="full URL", null=True),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="photo",
            field=models.ImageField(upload_to="organizers/"),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="twitter",
            field=models.URLField(blank=True, help_text="full URL", null=True),
        ),
    ]
