# Generated by Django 4.1.7 on 2023-05-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="photo",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="talk",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="og:image (social media image) 1200×630 pixels",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="og:image (social media image) 1200×630 pixels",
                null=True,
                upload_to="",
            ),
        ),
    ]
