# Generated by Django 4.1.7 on 2023-05-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0002_alter_speaker_photo_alter_talk_og_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talk",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=16,
            ),
        ),
    ]
