# Generated by Django 4.2.1 on 2023-08-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0004_rename_difficulty_talk_minimum_python_knowledge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talk",
            name="minimum_topic_knowledge",
            field=models.CharField(
                choices=[
                    ("no-previous-knowledge", "No previous knowledge needed"),
                    ("few-times", "Attendees who used it few times"),
                    ("regular-basis", "Attendees who use it on a regular basis"),
                ],
                default="no-previous-knowledge",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="track",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("pydata", "PyData"),
                    ("beginners", "Beginners"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="minimum_topic_knowledge",
            field=models.CharField(
                choices=[
                    ("no-previous-knowledge", "No previous knowledge needed"),
                    ("few-times", "Attendees who used it few times"),
                    ("regular-basis", "Attendees who use it on a regular basis"),
                ],
                default="no-previous-knowledge",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="track",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("pydata", "PyData"),
                    ("beginners", "Beginners"),
                ],
                max_length=16,
            ),
        ),
    ]
