# Generated by Django 4.2.1 on 2023-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0005_session_alter_knowledge_and_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="pretalx_code",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="pretalx_code",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="pretalx_code",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True, unique=True
            ),
        ),
    ]
