# Generated by Django 4.2.1 on 2023-08-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0007_alter_talk_order_alter_workshop_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
