# Generated by Django 4.2.1 on 2023-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0008_alter_speaker_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talk",
            name="track",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("pydata", "PyData"),
                    ("beginners", "Beginners"),
                    ("keynote", "Keynote"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="track",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("pydata", "PyData"),
                    ("beginners", "Beginners"),
                    ("keynote", "Keynote"),
                ],
                max_length=16,
            ),
        ),
    ]
