# Generated by Django 4.2.1 on 2023-08-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0009_alter_talk_track_alter_workshop_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="pretalx_code",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="talk",
            name="pretalx_code",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="pretalx_code",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
