# Generated by Django 4.2.1 on 2023-08-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0011_alter_talk_video_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speaker",
            name="display_position",
        ),
        migrations.AddField(
            model_name="speaker",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="display order on front end (lower the number, higher it is)",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("cs", "Czech/Slovak")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="order",
            field=models.SmallIntegerField(
                default=500,
                help_text="display order on front end (lower the number, higher it is)",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="type",
            field=models.CharField(
                choices=[
                    ("workshop", "Workshop"),
                    ("sprint", "Sprint"),
                    ("talk", "Talk"),
                    ("panel", "Panel"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("cs", "Czech/Slovak")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="order",
            field=models.SmallIntegerField(
                default=500,
                help_text="display order on front end (lower the number, higher it is)",
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="type",
            field=models.CharField(
                choices=[
                    ("workshop", "Workshop"),
                    ("sprint", "Sprint"),
                    ("talk", "Talk"),
                    ("panel", "Panel"),
                ],
                max_length=10,
            ),
        ),
    ]
