# Generated by Django 4.2.1 on 2023-08-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0012_remove_speaker_display_position_speaker_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speaker",
            options={"ordering": ("order",)},
        ),
        migrations.AlterField(
            model_name="speaker",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=500,
                help_text="display order on front end (lower the number, higher it is)",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=500,
                help_text="display order on front end (lower the number, higher it is)",
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=500,
                help_text="display order on front end (lower the number, higher it is)",
            ),
        ),
    ]
