# Generated by Django 4.2.1 on 2023-08-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0013_alter_speaker_options_alter_speaker_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="github",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="linkedin",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="personal_website",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="twitter",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="talk",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="og:image (social media image) 1200×630 pixels",
                null=True,
                upload_to="og-images/program/",
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="og:image (social media image) 1200×630 pixels",
                null=True,
                upload_to="og-images/program/",
            ),
        ),
    ]
