# Generated by Django 4.2.1 on 2023-08-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0018_room_alter_slot_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="object_id",
        ),
        migrations.AddField(
            model_name="slot",
            name="talk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="program.talk",
            ),
        ),
        migrations.AddField(
            model_name="slot",
            name="utility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="program.utility",
            ),
        ),
        migrations.AddField(
            model_name="slot",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="program.workshop",
            ),
        ),
    ]
