# Generated by Django 4.2.1 on 2023-08-29 13:45

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils.text import slugify


def populate_room_slugs(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    room_model: models.Model = apps.get_model("program", "Room")
    db_alias = schema_editor.connection.alias

    all_rooms = room_model.objects.using(db_alias).all()
    for room in all_rooms:
        room.slug = slugify(room.label)
    room_model.objects.bulk_update(all_rooms, fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0019_remove_slot_content_type_remove_slot_object_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=populate_room_slugs,
            reverse_code=migrations.RunPython.noop,
        )
    ]
