# Generated by Django 4.2.1 on 2023-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0020_room_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ("order", "id")},
        ),
        migrations.RemoveField(
            model_name="room",
            name="floor",
        ),
        migrations.AddField(
            model_name="room",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="display order on front end (lower the number, higher it is)",
            ),
        ),
        migrations.AddField(
            model_name="utility",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="utility",
            name="description",
            field=models.TextField(
                blank=True, help_text="markdown formatted", null=True
            ),
        ),
        migrations.AlterField(
            model_name="utility",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="whole item will be a link to this URL",
                max_length=255,
                null=True,
                verbose_name="URL",
            ),
        ),
    ]
