# Generated by Django 4.2.1 on 2023-11-01 10:05

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0021_alter_room_options_remove_room_floor_room_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talk",
            name="video_id",
        ),
        migrations.AddField(
            model_name="talk",
            name="video_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="video-images/session/"
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="video_url",
            field=models.CharField(
                blank=True,
                help_text="YouTube video URL: <code>https://www.youtube.com/watch?v=&lt;VIDEO_ID&gt;</code>. Do not include any additional parameters, such as start time or tracking (UTM) parameters.",
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_youtube_url",
                        message="Invalid YouTube URL format.",
                        regex=re.compile(
                            "^https://www\\.youtube\\.com/watch\\?v=(?P<video_id>[0-9A-Za-z_-]{11,})$"
                        ),
                    )
                ],
                verbose_name="Video URL",
            ),
        ),
    ]
