# Generated by Django 4.2.1 on 2023-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0022_talk_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="slides_description",
            field=models.TextField(
                blank=True,
                help_text="Additional text that will be displayed under the file to download. Use it to link GitHub repo with examples, additional materials etc. You can use Markdown syntax.",
                null=True,
                verbose_name="Slides Description",
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="slides_file",
            field=models.FileField(
                blank=True,
                help_text="File for download, please use a PDF file.",
                null=True,
                upload_to="slides/session",
                verbose_name="Slides",
            ),
        ),
    ]
