# Generated by Django 4.1.7 on 2023-04-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Platinum"),
                            (2, "Gold"),
                            (3, "Silver"),
                            (4, "Bronze"),
                            (5, "Diversity"),
                            (6, "Media"),
                            (7, "Partners"),
                            (9, "Connectivity"),
                        ],
                        default=3,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        help_text="SVG only",
                        null=True,
                        upload_to="sponsors/images/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Markdown formatted", null=True
                    ),
                ),
                ("link_url", models.URLField()),
                (
                    "twitter",
                    models.URLField(blank=True, help_text="full URL", null=True),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, help_text="full URL", null=True),
                ),
                ("published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
    ]
