# Generated by Django 4.1.7 on 2023-05-24 21:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorsOffer",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("about", wagtail.fields.RichTextField(blank=True)),
                ("benefits", wagtail.fields.RichTextField(blank=True)),
                ("event_summary", wagtail.fields.RichTextField(blank=True)),
                ("custom_sponsorship", wagtail.fields.RichTextField(blank=True)),
                ("contacts", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="description",
            field=models.TextField(
                blank=True, help_text="markdown formatted", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=models.FileField(
                blank=True, help_text="SVG only", null=True, upload_to=""
            ),
        ),
    ]
