# Generated by Django 4.1.7 on 2023-04-08 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("sponsors", "0002_sponsorsofferpage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SponsorsOfferPage",
            new_name="SponsorsOffer",
        ),
    ]
