# Generated by Django 4.2.1 on 2023-08-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0002_sponsorsoffer_alter_sponsor_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="linkedin",
            field=models.URLField(blank=True, help_text="full URL", null=True),
        ),
        migrations.DeleteModel(
            name="SponsorsOffer",
        ),
    ]
