# Generated by Django 4.1.7 on 2023-04-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0003_rename_sponsorsofferpage_sponsorsoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="description",
            field=models.TextField(
                blank=True, help_text="markdown formatted", null=True
            ),
        ),
    ]
