# Generated by Django 4.2.1 on 2023-08-22 17:56

from django.db import migrations, models
import django.db.models.deletion


def migrate_level_data(apps, schema_editor):
    Sponsor = apps.get_model("sponsors", "Sponsor")
    Level = apps.get_model("sponsors", "Level")

    for sponsor in Sponsor.objects.all():
        level = Level.objects.get(order=sponsor.level)
        sponsor.level_fk = level
        sponsor.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0004_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="level_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sponsors.level",
            ),
        ),
        migrations.RunPython(migrate_level_data),
    ]
