# Generated by Django 4.2.1 on 2023-08-22 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0005_sponsor_level_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsor",
            name="level",
        ),
        migrations.RenameField(
            model_name="sponsor",
            old_name="level_fk",
            new_name="level",
        ),
    ]
