# Generated by Django 4.2.1 on 2023-08-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0006_remove_sponsor_level_rename_level_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={"ordering": ["order", "title"]},
        ),
        migrations.AlterField(
            model_name="level",
            name="order",
            field=models.PositiveIntegerField(
                help_text="display order on front end (lower the number, the higher it is)"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="size",
            field=models.PositiveIntegerField(
                default=0, help_text="visual size (lower the number, the bigger it is)"
            ),
        ),
    ]
