# Generated by Django 4.1.7 on 2023-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="markdown formatted")),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "font_size",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Large"),
                            (2, "Medium"),
                            (3, "Small"),
                            (4, "Extra Small"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
