# Generated by Django 4.2.1 on 2023-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="font_size",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="position",
        ),
        migrations.AddField(
            model_name="announcement",
            name="order",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="announcement",
            name="size",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Extra Large"),
                    (2, "Large"),
                    (3, "Medium"),
                    (4, "Small"),
                    (5, "Extra Small"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="message",
            field=models.TextField(help_text="Markdown flavoured"),
        ),
    ]
