on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build docker image, lint and run tests
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        id: build
        uses: docker/build-push-action@v2
        with:
          tags: pycon:latest
          push: false

      # TODO: this will fail because the code doesnt pass the lint checks yet.
      # Fix the errors and re-enable linters
      #- name: Lint
      #  uses: addnab/docker-run-action@v3
      #  id: lint
      #  with:
      #    image: pycon:latest
      #    run: make ci/lint

      - name: Run tests
        uses: addnab/docker-run-action@v3
        id: test
        with:
          image: pycon:latest
          run: make ci/test

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

